version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: nltk
    versions:
    - 3.6.1
  - dependency-name: pandas
    versions:
    - 1.2.1
    - 1.2.2
    - 1.2.3
  - dependency-name: azure-storage-blob
    versions:
    - 12.8.0
  - dependency-name: apache-airflow
    versions:
    - 2.0.0
    - 2.0.1
