trigger:
- master

variables:
  vmImage: 'ubuntu-16.04'
  python_version: '3.7'

stages:
- stage: prebuild
  jobs:
  - job: 'code_check'
    pool:
      vmImage: $(vmImage)
    strategy:
      matrix:
        Python37:
          python.version: $(python_version)
    continueOnError: true

    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '$(python.version)'

    - script: |
        python -m compileall .
      displayName: 'Compile solution'

    - script: |
        python -m pip install flake8
        flake8 ./pliptv
      displayName: 'Run lint tests'

  - job: 'type_check'
    pool:
      vmImage: $(vmImage)
    strategy:
      matrix:
        Python37:
          python.version: $(python_version)
    continueOnError: true
    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '$(python.version)'
    - script: |
        python -m pip install mypy
        make typecheck
      displayName: 'Run typecheck'

- stage: test
  jobs:
  - job: 'tests'
    pool:
      vmImage: $(vmImage)
    strategy:
      matrix:
        Python37:
          python.version: '3.7'
    displayName: Tests

    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '$(python.version)'

    - script: |
        pip install codecov
        pip install -r requirements.txt -r requirements-dev.txt
        coverage erase
        coverage run -m unittest discover -p '*_test.py'
        coverage report -m
        coverage html
        codecov --token $CODECOV_TOKEN
      displayName: 'Test with pytest && publish code coverage'
      env:
        CODECOV_TOKEN: $(CODECOV_TOKEN)
        PL: $(PL)
        EPG_INDEX_URL: $(EPG_INDEX_URL)

    - task: PublishCodeCoverageResults@1
      inputs:
        codeCoverageTool: Cobertura
        summaryFileLocation: '$(System.DefaultWorkingDirectory)/**/coverage.xml'
        reportDirectory: '$(System.DefaultWorkingDirectory)/**/htmlcov'

    - script: |
        pip install -r requirements.txt -r requirements-dev.txt
        python -m xmlrunner discover -p '*_test.py' -o ./build/reports
      env:
        PL: $(PL)
        EPG_INDEX_URL: $(EPG_INDEX_URL)
      displayName: 'Unittests generate reports'

    - task: PublishTestResults@2
      condition: succeededOrFailed()
      inputs:
        testResultsFiles: '$(System.DefaultWorkingDirectory)/build/reports/TEST-*.xml'
        testRunTitle: 'Publish test results for Python $(python.version)'

- template: templates/stage-build-package.yaml

- template: templates/stage-deploy.yaml
  parameters:
    name: Deploy-TEST
    vmImage: $(vmImage)
    environment: test_pypi

- template: templates/stage-deploy.yaml
  parameters:
    name: Deploy-PROD
    vmImage: $(vmImage)
    environment: prod_pypi

#      TODO: Add approver to prod env
#      TODO: Create pipeline template for publishing pypi package
#      TODO: Bumpversion with git tags

