parameters:
  vmImage: 'Ubuntu-16.04'
  environment: 'dev'

stages:
- stage: DeployPackage_${{parameters.environment}}
  displayName: DeployPackage_${{parameters.environment}}
  condition: succeeded()
  dependsOn: BuildPackage
  jobs:
  - deployment: DeployPackage
    pool:
      vmImage: ${{ parameters.vmImage }}
    environment: ${{ parameters.environment }}
    displayName: "Deploy to ${{ parameters.environment }}"
    strategy:
      runOnce:
        deploy:
          steps:
            - download: none

            - task: DownloadBuildArtifacts@0
              inputs:
                buildType: current
                downloadType: single
                artifactName: xpl
                downloadPath: '$(System.ArtifactsDirectory)'

            - script: |
                pip install twine
              displayName: Twine installion

            - task: TwineAuthenticate@1
              displayName: 'Twine Authenticate to ${{ parameters.environment }}'
              inputs:
                pythonUploadServiceConnection: ${{ parameters.environment }}

            - script: |
                python -m twine upload --verbose -r "${{ parameters.environment }}" --config-file $(PYPIRC_PATH) '$(System.ArtifactsDirectory)/xpl/dist/*'
              displayName: 'Publishing package to ${{ parameters.environment }}'