parameters:
  vmImage: 'Ubuntu-16.04'
  environment: 'dev'
  condition: true

stages:
- stage: DeployPackage_${{parameters.environment}}
  displayName: DeployPackage_${{parameters.environment}}
  condition: ${{ parameters.condition }}
  dependsOn: BuildPackage
  jobs:
  - deployment: DeployPackage
    pool:
      vmImage: ${{ parameters.vmImage }}
    environment: ${{ parameters.environment }}
    displayName: "Deploy to ${{ parameters.environment }}"
    strategy:
      runOnce:
        deploy:
          steps:
            - download: none

            - task: UsePythonVersion@0
              inputs:
                versionSpec: '3.7'
                targetType: 'inline'

            - task: DownloadBuildArtifacts@0
              inputs:
                buildType: current
                downloadType: single
                artifactName: xpl
                downloadPath: '$(System.ArtifactsDirectory)'

            - script: |
                pip install twine
              displayName: Twine install

            - task: TwineAuthenticate@1
              displayName: 'Twine Authenticate to ${{ parameters.environment }}'
              inputs:
                pythonUploadServiceConnection: ${{ parameters.environment }}

            - script: |
                python -m twine upload --skip-existing -r "${{ parameters.environment }}" --config-file $(PYPIRC_PATH) "$(System.ArtifactsDirectory)/xpl/dist/*"
              displayName: 'Publishing package to ${{ parameters.environment }}'
